### ISSUE TITLE
planer videre

### ISSUE THREAD

**Issue by nilsmagnus** [Utdanningsdirektoratet/KL06-LK20-public#10]
Er dette prosjektet dødt nå, eller er det planlagt å gå ut av beta?

**Comment by aremjolsnes** [comment]
Hei,
Prosjektet er på ingen måte dødt - det er i produksjon.
Som det antydes i README.md, så ble eksempelfilene her laget før vi kunne vise noe "live". Derfor kan eksempelfilene avvike noe fra det som kom i produskjon nå i høst. Jeg skal sørge for å skrive en tydeligere status på dette i README-fila, og beklager at det ikke er gjort tidligere.

Du kan lese mer om hvordan du kan bruke Grep-data på https://www.udir.no/om-udir/data/kl06-grep/

Du er også velkommen til å følge oss og delta på vår offisielle Slack-kanal (se invitasjonslenke i lenken over).
